name: Node.js Package
# 监测图床分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python -m pip install --upgrade pip
        
      - name: run  scripts
       
        run: |
          python main.py
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
