name: run npm-version pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: 'change version'
        uses: polygon-software/npm-version-date@master
        with:
          schema: 'V.yyMM.P'
          V: '2'
          increase-patch: true