name: Node.js Package
# 监测图床分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install
    - name: Deploying version
      uses: ./
      with:
        pkg_name: package-deployer
        pkg_managers: '[github, npm]'
        npm_registry: registry.npmjs.org
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}
        dry_run: true
        debug: true
